name: ICLNashville
favicon: null
layout_spectrum: 0.9964170111343265
typography_spectrum: 0.6187245470937341
title: 'International Concierge & Logistics'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6763518282677978
  lightness: 0.685450121993199
  saturation: 0.670425413409248
  rhythmicContrast: 0.6836917591281235
purpose: []
