name: ICLNashville
favicon: null
layout_spectrum: 0
typography_spectrum: 0.87874
title: 'International Concierge & Logistics'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.6836917591281235
purpose: []
